2020-12-15 20:14:07 INFO: Access Token has expired. Hence refreshing.
2020-12-15 20:14:07 SEVERE: Exception occured while Saving OAuthTokens to file(file::ZohoOAuthPersistenceByFile)(file_put_contents(http://localhost/portal/public/token/zcrm_oauthtokens.txt): failed to open stream: HTTP wrapper does not support writeable connections)
ErrorException: file_put_contents(http://localhost/portal/public/token/zcrm_oauthtokens.txt): failed to open stream: HTTP wrapper does not support writeable connections in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\persistence\ZohoOAuthPersistenceByFile.php:90
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_put_conten...', 'C:\\xampp\\htdocs...', 90, Array)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(90): file_put_contents('http://localhos...', 'a:0:{}')
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(23): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->deleteOAuthTokens('tecnologia@grup...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\ZohoOAuthClient.php(97): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->saveOAuthData(Object(zcrmsdk\oauth\utility\ZohoOAuthTokens))
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\ZohoOAuthClient.php(47): zcrmsdk\oauth\ZohoOAuthClient->refreshAccessToken('1000.6a6daa16fb...', 'tecnologia@grup...')
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('tecnologia@grup...')
#6 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#7 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#8 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#9 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#10 C:\xampp\htdocs\portal\app\Models\Usuario.php(16): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#11 C:\xampp\htdocs\portal\app\Controllers\Login.php(17): App\Models\Usuario->validar('warlyn200@gmail...', 'asd')
#12 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#13 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#14 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#16 {main}
2020-12-15 20:14:08 SEVERE: Exception occured while Saving OAuthTokens to file(file::ZohoOAuthPersistenceByFile)(file_put_contents(http://localhost/portal/public/token/zcrm_oauthtokens.txt): failed to open stream: HTTP wrapper does not support writeable connections)
ErrorException: file_put_contents(http://localhost/portal/public/token/zcrm_oauthtokens.txt): failed to open stream: HTTP wrapper does not support writeable connections in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\persistence\ZohoOAuthPersistenceByFile.php:90
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_put_conten...', 'C:\\xampp\\htdocs...', 90, Array)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(90): file_put_contents('http://localhos...', 'a:0:{}')
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(23): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->deleteOAuthTokens('tecnologia@grup...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\ZohoOAuthClient.php(97): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->saveOAuthData(Object(zcrmsdk\oauth\utility\ZohoOAuthTokens))
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\oauth\ZohoOAuthClient.php(47): zcrmsdk\oauth\ZohoOAuthClient->refreshAccessToken('1000.6a6daa16fb...', 'tecnologia@grup...')
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('tecnologia@grup...')
#6 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#7 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#8 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#9 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#10 C:\xampp\htdocs\portal\app\Models\Usuario.php(16): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#11 C:\xampp\htdocs\portal\app\Controllers\Login.php(17): App\Models\Usuario->validar('warlyn200@gmail...', 'asd')
#12 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#13 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#14 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#16 {main}
2020-12-15 20:15:16 INFO: Access Token has expired. Hence refreshing.
2020-12-15 20:15:18 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#6 C:\xampp\htdocs\portal\app\Models\Usuario.php(16): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Login.php(17): App\Models\Usuario->validar('warlyn200@gmail...', 'asd')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-15 20:23:43 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#6 C:\xampp\htdocs\portal\app\Models\Usuario.php(33): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Login.php(17): App\Models\Usuario->validar('alba@gruponobe....', 'asd')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-15 20:41:15 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#6 C:\xampp\htdocs\portal\app\Models\Usuario.php(33): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Login.php(17): App\Models\Usuario->validar('lcastillo@banco...', 'admidn')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 07:27:59 INFO: Access Token has expired. Hence refreshing.
2020-12-16 07:28:02 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid query formed' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(72)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Account_Name:eq...')
#6 C:\xampp\htdocs\portal\app\Models\Cotizacion.php(16): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Account_Name:eq...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Home.php(16): App\Models\Cotizacion->lista()
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Home->index()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 07:28:34 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid query formed' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(72)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Account_Name:eq...')
#6 C:\xampp\htdocs\portal\app\Models\Cotizacion.php(16): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Account_Name:eq...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Home.php(16): App\Models\Cotizacion->lista()
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Home->index()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 07:45:46 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Account_Name:eq...')
#6 C:\xampp\htdocs\portal\app\Models\Cotizacion.php(16): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Account_Name:eq...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(12): App\Models\Cotizacion->lista('3', 10)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->index('3')
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 07:45:53 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Account_Name:eq...')
#6 C:\xampp\htdocs\portal\app\Models\Cotizacion.php(16): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Account_Name:eq...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(12): App\Models\Cotizacion->lista('3', 10)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->index('3')
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 08:31:47 INFO: Access Token has expired. Hence refreshing.
2020-12-16 09:33:27 INFO: Access Token has expired. Hence refreshing.
2020-12-16 10:36:30 INFO: Access Token has expired. Hence refreshing.
2020-12-16 13:05:59 INFO: Access Token has expired. Hence refreshing.
2020-12-16 14:55:50 INFO: Access Token has expired. Hence refreshing.
2020-12-16 15:48:47 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#6 C:\xampp\htdocs\portal\app\Models\Usuario.php(26): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Login.php(17): App\Models\Usuario->validar('warlyn200@gmail...', 'admin')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 15:49:06 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#6 C:\xampp\htdocs\portal\app\Models\Usuario.php(26): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Login.php(17): App\Models\Usuario->validar('alba@gruponobe....', 'asd')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 15:49:20 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#6 C:\xampp\htdocs\portal\app\Models\Usuario.php(26): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Login.php(17): App\Models\Usuario->validar('alba@gruponobe....', 'asd')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 15:56:26 INFO: Access Token has expired. Hence refreshing.
2020-12-16 16:56:03 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(67): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos('322237300000883...', '322237300000883...')
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 16:56:09 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(67): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos('322237300000883...', '322237300000883...')
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 16:56:23 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(67): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos('322237300000883...', '322237300000883...')
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 16:57:53 INFO: Access Token has expired. Hence refreshing.
2020-12-16 16:57:54 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(67): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos('322237300000883...', '322237300000883...')
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 16:58:45 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(68): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos(Array)
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 16:59:41 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(68): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos(Array)
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 16:59:59 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(68): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos(Array)
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 17:00:03 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(68): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos(Array)
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 17:00:11 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(68): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos(Array)
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 17:00:31 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 404 \r\n...', 404)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\RelatedListAPIHandler.php(271): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModuleRelation.php(198): zcrmsdk\crm\api\handler\RelatedListAPIHandler->downloadAttachment('322237300000883...')
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(765): zcrmsdk\crm\crud\ZCRMModuleRelation->downloadAttachment('322237300000883...')
#4 C:\xampp\htdocs\portal\app\Models\Plan.php(46): zcrmsdk\crm\crud\ZCRMRecord->downloadAttachment('322237300000883...')
#5 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(68): App\Models\Plan->descargarAdjunto('Products', '322237300000883...', '322237300000883...', 'http://localhos...')
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->adjuntos(Array)
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-16 17:14:31 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'the id given seems to be invalid' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\FileAPIResponse.php(97)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(236): zcrmsdk\crm\api\response\FileAPIResponse->setFileContent('HTTP/1.1 400 \r\n...', 400)
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\EntityAPIHandler.php(248): zcrmsdk\crm\api\APIRequest->downloadFile()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMRecord.php(797): zcrmsdk\crm\api\handler\EntityAPIHandler->downloadPhoto()
#3 C:\xampp\htdocs\portal\app\Models\Plan.php(61): zcrmsdk\crm\crud\ZCRMRecord->downloadPhoto()
#4 C:\xampp\htdocs\portal\app\Views\cotizaciones\descargar.php(180): App\Models\Plan->descargarImagen('322237300000594...')
#5 C:\xampp\htdocs\portal\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\portal\system\Common.php(1119): CodeIgniter\View\View->render('cotizaciones/de...', Array, true)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(92): view('cotizaciones/de...', Array)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->descargar('322237300000980...')
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-16 20:03:35 INFO: Access Token has expired. Hence refreshing.
2020-12-16 21:06:23 INFO: Access Token has expired. Hence refreshing.
2020-12-17 07:38:46 INFO: Access Token has expired. Hence refreshing.
2020-12-17 07:38:48 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(37): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Login.php(22): App\Libraries\Zoho->searchRecordsByCriteria('Contacts', '((Email:equals:...', 1, 1)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-17 07:38:55 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'current user should either be set in ZCRMRestClient or in configuration map' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\utility\ZCRMConfigUtil.php(99)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Account_Name:eq...')
#4 C:\xampp\htdocs\portal\app\Models\Cotizacion.php(16): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Account_Name:eq...', Array)
#5 C:\xampp\htdocs\portal\app\Controllers\Home.php(20): App\Models\Cotizacion->lista()
#6 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Home->index()
#7 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
2020-12-17 07:50:32 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'INVALID_DATA-The given id seems to be invalid.' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(88)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204, NULL)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\EntityAPIHandler.php(45): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord(Array, Array)
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(69): zcrmsdk\crm\crud\ZCRMModule->getRecord('322237300000883...')
#7 C:\xampp\htdocs\portal\app\Views\cotizaciones\detalles.php(97): App\Libraries\Zoho->getRecord('Vendors', '322237300000883...')
#8 C:\xampp\htdocs\portal\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\portal\system\Common.php(1119): CodeIgniter\View\View->render('cotizaciones/de...', Array, true)
#10 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(34): view('cotizaciones/de...', Array)
#11 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->detalles('322237300000980...')
#12 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#13 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#15 {main}
2020-12-17 08:38:52 INFO: Access Token has expired. Hence refreshing.
2020-12-17 10:33:42 INFO: Access Token has expired. Hence refreshing.
2020-12-18 07:55:31 INFO: Access Token has expired. Hence refreshing.
2020-12-18 08:25:17 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Account_Name:eq...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Account_Name:eq...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(17): App\Libraries\Zoho->searchRecordsByCriteria('Quotes', 'Account_Name:eq...', '4', 15)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->index('4')
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 08:26:33 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Account_Name:eq...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Account_Name:eq...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(17): App\Libraries\Zoho->searchRecordsByCriteria('Quotes', 'Account_Name:eq...', '3', 15)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->index('3')
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 08:33:35 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Email:equals:...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Email:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Login.php(22): App\Libraries\Zoho->searchRecordsByCriteria('Contacts', '((Email:equals:...', 1, 1)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Login->ingresar()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:06:35 INFO: Access Token has expired. Hence refreshing.
2020-12-18 09:21:24 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:21:47 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:22:12 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:23:02 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:23:59 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:24:28 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:27:29 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:27:47 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:28:09 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:28:55 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:29:01 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:29:04 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:29:47 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(93)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\EntityAPIHandler.php(45): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord(Array, Array)
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(71): zcrmsdk\crm\crud\ZCRMModule->getRecord(' 32223730000057...')
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->getRecord('Marcas', ' 32223730000057...')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:29:51 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(93)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\EntityAPIHandler.php(45): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord(Array, Array)
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(71): zcrmsdk\crm\crud\ZCRMModule->getRecord(' 32223730000057...')
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->getRecord('Marcas', ' 32223730000057...')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:31:04 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:31:07 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:31:12 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:31:58 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(93)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\EntityAPIHandler.php(45): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord(Array, Array)
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(71): zcrmsdk\crm\crud\ZCRMModule->getRecord(' 32223730000057...')
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->getRecord('Marcas', ' 32223730000057...')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:33:23 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(93)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\EntityAPIHandler.php(45): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord(Array, Array)
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(71): zcrmsdk\crm\crud\ZCRMModule->getRecord(' 32223730000057...')
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->getRecord('Marcas', ' 32223730000057...')
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:34:55 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(41): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:36:22 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:37:34 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:37:36 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:40:08 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:40:10 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:40:38 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:40:40 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:41:03 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(44): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:41:05 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(44): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:41:42 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals: 3...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals: 3...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(44): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals: 3...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:42:16 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals:32...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals:32...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(44): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals:32...', 2, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:53:01 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals:32...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals:32...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals:32...', 4, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:58:35 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals:32...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals:32...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals:32...', 2, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:58:41 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Marca:equals:...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Marca:equals:...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(77): App\Libraries\Zoho->searchRecordsByCriteria('Restringidos', '((Marca:equals:...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->cotizarAuto()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:58:42 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Modelo:equals...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Modelo:equals...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(85): App\Libraries\Zoho->searchRecordsByCriteria('Restringidos', '((Modelo:equals...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->cotizarAuto()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:58:44 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Plan:equals:322...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Plan:equals:322...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(105): App\Libraries\Zoho->searchRecordsByCriteria('Recargos', 'Plan:equals:322...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->cotizarAuto()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:58:45 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Modelo:equals...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Modelo:equals...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(85): App\Libraries\Zoho->searchRecordsByCriteria('Restringidos', '((Modelo:equals...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->cotizarAuto()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:58:47 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Plan:equals:322...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Plan:equals:322...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(105): App\Libraries\Zoho->searchRecordsByCriteria('Recargos', 'Plan:equals:322...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->cotizarAuto()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 09:58:48 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(61)
Trace::#0 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\api\handler\MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\portal\vendor\zohocrm\php-sdk-archive\src\crm\crud\ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Modelo:equals...')
#6 C:\xampp\htdocs\portal\app\Libraries\Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Modelo:equals...', Array)
#7 C:\xampp\htdocs\portal\app\Controllers\Cotizaciones.php(85): App\Libraries\Zoho->searchRecordsByCriteria('Restringidos', '((Modelo:equals...', 1, 200)
#8 C:\xampp\htdocs\portal\system\CodeIgniter.php(871): App\Controllers\Cotizaciones->cotizarAuto()
#9 C:\xampp\htdocs\portal\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 C:\xampp\htdocs\portal\system\CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\portal\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-18 10:07:33 INFO: Access Token has expired. Hence refreshing.
2020-12-18 19:25:24 INFO: Access Token has expired. Hence refreshing.
2020-12-21 16:38:05 INFO: Access Token has expired. Hence refreshing.
2020-12-21 16:40:10 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(61)
Trace::#0 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/handler/MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Marca:equals:32...')
#6 /opt/lampp/htdocs/portal/app/Libraries/Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Marca:equals:32...', Array)
#7 /opt/lampp/htdocs/portal/app/Controllers/Cotizaciones.php(43): App\Libraries\Zoho->searchRecordsByCriteria('Modelos', 'Marca:equals:32...', 2, 200)
#8 /opt/lampp/htdocs/portal/system/CodeIgniter.php(871): App\Controllers\Cotizaciones->modelos()
#9 /opt/lampp/htdocs/portal/system/CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 /opt/lampp/htdocs/portal/system/CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /opt/lampp/htdocs/portal/public/index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-21 18:26:37 INFO: Access Token has expired. Hence refreshing.
2020-12-21 18:27:14 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/APIResponse.php(93)
Trace::#0 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/handler/EntityAPIHandler.php(45): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 /opt/lampp/htdocs/portal/vendor/zohocrm/php-sdk-archive/src/crm/crud/ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord(Array, Array)
#6 /opt/lampp/htdocs/portal/app/Libraries/Zoho.php(71): zcrmsdk\crm\crud\ZCRMModule->getRecord('322237300000992...')
#7 /opt/lampp/htdocs/portal/app/Controllers/Cotizaciones.php(283): App\Libraries\Zoho->getRecord('Quotes', '322237300000992...')
#8 /opt/lampp/htdocs/portal/system/CodeIgniter.php(871): App\Controllers\Cotizaciones->detalles('322237300000992...')
#9 /opt/lampp/htdocs/portal/system/CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cotizaciones))
#10 /opt/lampp/htdocs/portal/system/CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /opt/lampp/htdocs/portal/public/index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-21 19:27:03 INFO: Access Token has expired. Hence refreshing.
2020-12-22 08:43:29 INFO: Access Token has expired. Hence refreshing.
2020-12-22 08:54:38 INFO: Access Token has expired. Hence refreshing.
2020-12-22 08:58:04 INFO: Access Token has expired. Hence refreshing.
2020-12-22 09:58:31 INFO: Access Token has expired. Hence refreshing.
2020-12-23 09:14:39 INFO: Access Token has expired. Hence refreshing.
2020-12-23 10:56:16 INFO: Access Token has expired. Hence refreshing.
2020-12-24 09:36:33 INFO: Access Token has expired. Hence refreshing.
2020-12-25 13:24:41 INFO: Access Token has expired. Hence refreshing.
2020-12-25 13:47:17 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(61)
Trace::#0 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct()
#3 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct()
#4 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/handler/MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords()
#6 /var/www/html/portal/app/Libraries/Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria()
#7 /var/www/html/portal/app/Controllers/Home.php(19): App\Libraries\Zoho->searchRecordsByCriteria()
#8 /var/www/html/portal/system/CodeIgniter.php(871): App\Controllers\Home->index()
#9 /var/www/html/portal/system/CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController()
#10 /var/www/html/portal/system/CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest()
#11 /var/www/html/portal/public/index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-25 13:47:26 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(61)
Trace::#0 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct()
#3 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct()
#4 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/handler/MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords()
#6 /var/www/html/portal/app/Libraries/Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria()
#7 /var/www/html/portal/app/Controllers/Home.php(19): App\Libraries\Zoho->searchRecordsByCriteria()
#8 /var/www/html/portal/system/CodeIgniter.php(871): App\Controllers\Home->index()
#9 /var/www/html/portal/system/CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController()
#10 /var/www/html/portal/system/CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest()
#11 /var/www/html/portal/public/index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-25 13:59:05 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(61)
Trace::#0 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct()
#3 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct()
#4 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/handler/MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords()
#6 /var/www/html/portal/app/Libraries/Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria()
#7 /var/www/html/portal/app/Controllers/Home.php(19): App\Libraries\Zoho->searchRecordsByCriteria()
#8 /var/www/html/portal/system/CodeIgniter.php(871): App\Controllers\Home->index()
#9 /var/www/html/portal/system/CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController()
#10 /var/www/html/portal/system/CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest()
#11 /var/www/html/portal/public/index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-25 14:05:27 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(61)
Trace::#0 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/response/BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct()
#3 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct()
#4 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/api/handler/MassEntityAPIHandler.php(335): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/html/portal/vendor/zohocrm/php-sdk-archive/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords()
#6 /var/www/html/portal/app/Libraries/Zoho.php(36): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria()
#7 /var/www/html/portal/app/Controllers/Cotizaciones.php(17): App\Libraries\Zoho->searchRecordsByCriteria()
#8 /var/www/html/portal/system/CodeIgniter.php(871): App\Controllers\Cotizaciones->index()
#9 /var/www/html/portal/system/CodeIgniter.php(390): CodeIgniter\CodeIgniter->runController()
#10 /var/www/html/portal/system/CodeIgniter.php(307): CodeIgniter\CodeIgniter->handleRequest()
#11 /var/www/html/portal/public/index.php(45): CodeIgniter\CodeIgniter->run()
#12 {main}
2020-12-25 14:24:43 INFO: Access Token has expired. Hence refreshing.
